[tool.black]
line-length = 120
target-version = ['py37']
include = '\.pyi?$'
exclude = '/(\.git|\.hg|\.mypy_cache|\.tox|\.venv|\.serverless|_build|buck-out|build|dist|node_modules)/'

[tool.isort]
# config compatible with Black
line_length = 120
multi_line_output = 3
force_grid_wrap = 0
use_parentheses = true
default_section = "THIRDPARTY"
include_trailing_comma = true
